name: Polymarket Bot

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Instalar pacotes
        run: pip install -r requeriments.txt
        
      - name: Rodar bot
        run: timeout 110m python main.py
